CREATE DATABASE IF NOT EXISTS bloodyYueDB;
USE bloodyYueDB;

CREATE TABLE IF NOT EXISTS settings (
  settingId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100),
  subtitle VARCHAR(255),
  contentHero VARCHAR(255),
  email VARCHAR(50) UNIQUE,
  abaut TEXT,
  work TEXT,
  redes JSON,
  usagePolicies VARCHAR(255),
  seoMeta JSON,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS users (
  userId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  birthday DATE,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  avatar VARCHAR(255),
  poster VARCHAR(255),
  isActive BOOLEAN DEFAULT FALSE,
  isVerified BOOLEAN DEFAULT FALSE,
  rolId INT UNSIGNED,
  status ENUM('active', 'inactive', 'banned') DEFAULT 'active',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX iUsers (name, email),
  FOREIGN KEY (rolId) REFERENCES roles(rolId)
);

CREATE TABLE IF NOT EXISTS codes (
  codeId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(255),
  deadLine DATETIME,
  userId INT UNSIGNED,
  type ENUM('verify', 'restartPassword'),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(userId)
);

CREATE TABLE IF NOT EXISTS roles (
  rolId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  description VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

/* create module rols */


CREATE TABLE IF NOT EXISTS permits (
  permitId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  titleBack VARCHAR(100),
  name VARCHAR(100),
  description VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rolXpermits (
  rxpId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  rolId INT UNSIGNED,
  permitId INT UNSIGNED,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (rolId) REFERENCES roles(rolId),
  FOREIGN KEY (permitId) REFERENCES permits(permitId)
);

CREATE TABLE IF NOT EXISTS testimonies (
  testimonyId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userId INT UNSIGNED,
  message VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(userId)
);

CREATE TABLE IF NOT EXISTS labels (
  labelId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  color CHAR(7),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS commissions (
  commissionId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  
  userId INT UNSIGNED, 
  // add new field
  
  title VARCHAR(100),
  content VARCHAR(255),
  exampleId INT UNSIGNED,
  description VARCHAR(255),
  price DECIMAL(10,2),
  terms TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(userId),
  FOREIGN KEY (exampleId) REFERENCES posts(postId)
);

CREATE TABLE IF NOT EXISTS cart (
  cartId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userId INT UNSIGNED,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(userId)
);

CREATE TABLE IF NOT EXISTS cartItems (
  cartItemId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  cartId INT UNSIGNED,
  commissionId INT UNSIGNED,
  quantity INT,
  status ENUM('selected', 'unavailable', 'discarded', 'purchased'),
  priceAtMoment DECIMAL(10,2),
  details VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (cartId) REFERENCES cart(cartId),
  FOREIGN KEY (commissionId) REFERENCES commissions(commissionId)
);

CREATE TABLE IF NOT EXISTS sales (
  saleId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  cartItemId INT UNSIGNED,
  total DECIMAL(10,2),
  /* ******************* */
  paymentMethod VARCHAR(100),
  /* ******************* */
  status ENUM('initiated', 'paid', 'cancelled') DEFAULT 'initiated',

  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (cartItemId) REFERENCES cartItems(cartItemId)
);

CREATE TABLE IF NOT EXISTS detailsSale (
  detailsSaleId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  saleId INT UNSIGNED,
  status ENUM('pending', 'process', 'done'),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (saleId) REFERENCES sales(saleId)
);


CREATE TABLE IF NOT EXISTS chats (
  chatId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userId INT UNSIGNED,
  isActive BOOLEAN DEFAULT FALSE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(userId)
);

CREATE TABLE IF NOT EXISTS chatItems (
  chatItemId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  chatId INT UNSIGNED,
  userId INT UNSIGNED,
  message VARCHAR(255),
  isRead VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (chatId) REFERENCES chats(chatId),
  FOREIGN KEY (userId) REFERENCES users(userId)
);

CREATE TABLE IF NOT EXISTS commissionsXlabels (
  lxcId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  commissionId INT UNSIGNED,
  labelId INT UNSIGNED,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (commissionId) REFERENCES commissions(commissionId),
  FOREIGN KEY (labelId) REFERENCES labels(labelId)
);

CREATE TABLE IF NOT EXISTS posts (
  postId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userId INT UNSIGNED,
  title VARCHAR(100),
  description VARCHAR(255),
  content VARCHAR(255),
  typePost ENUM('image', 'short'),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(userId)
);

/* delete typePosts */

CREATE TABLE IF NOT EXISTS labelsXposts (
  lxpId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  postId INT UNSIGNED,
  labelId INT UNSIGNED,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (postId) REFERENCES posts(postId),
  FOREIGN KEY (labelId) REFERENCES labels(labelId)
);

CREATE TABLE IF NOT EXISTS postsReactions (
  reactionId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  postId INT UNSIGNED,
  userId INT UNSIGNED,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (postId) REFERENCES posts(postId),
  FOREIGN KEY (userId) REFERENCES users(userId)
);

CREATE TABLE IF NOT EXISTS notifications (  
  notificationId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userId INT UNSIGNED,
  type ENUM('reaction', 'sale', 'message', 'post', 'other'),
  message VARCHAR(255),
  isRead BOOLEAN DEFAULT FALSE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(userId)
);












/* configuration: tokens */

CREATE TABLE IF NOT EXISTS refreshTokens (
  refreshTokenId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userId INT UNSIGNED,
  token VARCHAR(255),
  expiresAt TIMESTAMP,
  isRevoked BOOLEAN DEFAULT FALSE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(userId)
);